services:
  server:
    working_dir: '/app'
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: 'swoole'
    ports:
      - "9501:9501"
    volumes:
      - ".:/app"

  database:
    image: 'postgres:16-alpine'
    working_dir: /app
    volumes:
      - '.:/app'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hermes
    ports:
      - '54321:5432'