services:
  server:
    working_dir: '/app'
    build:
      context: .
      dockerfile: build/Dockerfile
    container_name: 'swoole'
    environment:
      - PHP_IDE_CONFIG=serverName=hermes # xdebug on phpstorm name of server in phpstorm
    ports:
      - "9501:9501"
    volumes:
      - ".:/app"
      - './build/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  database:
    image: 'postgres:16-alpine'
    working_dir: /app
    volumes:
      - '.:/app'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=hermes
    ports:
      - '54321:5432'